#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.56
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
