name: ci

on:
  push:
  schedule:
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Build ISO
        run: |
          pacman-key --init
          pacman-key --populate
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel archiso git
          ./mkrepo
          mkdir -p work out
          ./mkarchiso -v -w work -o out ./configs/
          rm -rf work
      - uses: actions/upload-artifact@v3
        with:
          name: archiso
          path: out/

